import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppProvider } from "@/contexts/AppContext";
import Navigation from "@/components/layout/Navigation";
import { FlightProvider } from "@/contexts/FlightContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background", inter.className)}>
        <FlightProvider>
          <AppProvider>
            <Navigation />
            <main>{children}</main>
          </AppProvider>
        </FlightProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
